In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics

In [240]:
m_="/Users/edoardo/LabB/sevn_output_Z0.0001A1L1/BHBHm_n_0001.csv"
_ ="/Users/edoardo/LabB/sevn_output_Z0.0001A1L1/BHBH_n_0001.csv"
m_1="/Users/edoardo/LabB/sevn_output_Z0.01A1L1/BHBHm_n_01.csv"
_1="/Users/edoardo/LabB/sevn_output_Z0.01A1L1/BHBH_n_01.csv"
BHBHm=pd.read_csv(m_,delimiter=",", usecols=(3, 8, 13, 14, 15), skiprows=0)
BHBH=pd.read_csv(_,delimiter=",", usecols=(3, 8, 13, 14, 15), skiprows=0)
BHBHm_1=pd.read_csv(m_1,delimiter=",", usecols=(3, 8, 13, 14, 15), skiprows=0)
BHBH_1=pd.read_csv(_1,delimiter=",", usecols=(3, 8, 13, 14, 15), skiprows=0)

print('BHBHm',len(BHBHm),'BHBH',len(BHBH),'BHBHm_1',len(BHBHm_1),'BHBH_1',len(BHBH_1),)

BHBHm 4312 BHBH 25748 BHBHm_1 3804 BHBH_1 27645


In [241]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import regularizers

In [254]:
# Carica il datase
def dati(data):
    dataset = np.array(data)

    x = dataset[:, 0:4]# Parametri del sistema
    x[:, 0:2] = x[:, 0:2].astype(float) * (2 * 10 ** 30)
    x[:, 2] = x[:, 3].astype(float) * 6.96e8

    y = dataset[:, 4]*(365 * 24 * 60 * 60 * 10**6)  # Tempo di merge
    N = len(x)
    
    perc_train=0.8
    # dim. of a sample
    L = len(x[0])
    print(L)

    for i in range(10):
        print(x[i],y[i])

    N_train = int(perc_train * N)
   
    print(f'data: {N}\ntrain: {N_train}')
    # Suddivide il dataset in set di addestramento e test

    (x_train, y_train) = (x[0:N_train],y[0:N_train])
    (x_test, y_test) = (x[N_train:],y[N_train:])
    print("Train:",len(x_train),"\t Validation:",len(x_test))
    print(len(x_train))
    return x_train, y_train,x_test, y_test

In [296]:
x_train, y_train,x_test, y_test=dati(BHBH)


4
[3.56126400e+31 3.16113800e+31 1.03534454e+07 1.48756400e-02] 1.27925090208e+17
[8.59895600e+31 6.82991000e+31 4.99120044e+08 7.17126500e-01] 5.4874879056e+23
[4.337136e+31 4.524006e+31 4.277790e+08 6.146250e-01] 3.12630149232e+23
[7.34582800e+31 5.33517400e+31 4.95499313e+07 7.11924300e-02] 2.98154021472e+19
[8.31850400e+31 6.89868600e+31 4.57377514e+06 6.57151600e-03] 7.4437006752e+21
[1.94834260e+31 3.19647400e+31 1.35281798e+07 1.94370400e-02] 4.7230489584e+17
[9.96503000e+31 8.10338000e+31 1.75118681e+08 2.51607300e-01] 1.0467476424e+25
[1.79942800e+32 8.38715000e+31 7.57434528e+07 1.08826800e-01] 2.00200114944e+28
[1.20627560e+32 1.01556220e+32 2.30590716e+08 3.31308500e-01] 7.4285823168e+27
[3.71591800e+31 1.60456560e+31 2.62101977e+08 3.76583300e-01] 2.28545460144e+20
data: 25748
train: 20598
Train: 20598 	 Validation: 5150
20598


In [297]:
# Preparazione dei dati
#scaler_x = StandardScaler()
scaler_x = MinMaxScaler(feature_range=(-1, 1))  # Imposta il range di output desiderato (min_value, max_value)
x_train_normalized = scaler_x.fit_transform(x_train)
x_test_normalized = scaler_x.transform(x_test)

#scaler_y =StandardScaler()  
scaler_y = MinMaxScaler(feature_range=(-1, 1))  # Imposta il range di output desiderato (min_value, max_value)
y_train_normalized = scaler_y.fit_transform(y_train.reshape(-1, 1))
y_test_normalized = scaler_y.transform(y_test.reshape(-1, 1))

  


xgboost

In [298]:
import numpy as np
import matplotlib.pyplot as plt
# AdaBoost Algorithm
from sklearn.ensemble import AdaBoostClassifier
# Gradient Boosting 
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import xgboost
from xgboost import XGBClassifier
from xgboost import plot_importance, to_graphviz, plot_tree
print("XGBoost version:",xgboost.__version__)
from xgboost import XGBRegressor
from sklearn.preprocessing import MinMaxScaler,StandardScaler

XGBoost version: 1.7.5


In [299]:
def fit(xgbr=XGBRegressor(),show=False):
    xgbr.fit(x_train_normalized,y_train_normalized)
    
    pred_normalized = xgbr.predict(x_test_normalized)
    pred_normalized = y_pred_normalized.reshape(-1, 1)  # Reshape to 2D array
    pred = abs(scaler_y.inverse_transform(y_pred_normalized))


    print(len(y_pred))
   
    
    print("Accuracy: {:.2f}".format(np.sqrt(mean_squared_error(pred, y_test))))
    return pred

In [300]:
pred=fit(XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8 ),show=True)

863


ValueError: Found input variables with inconsistent numbers of samples: [863, 5150]

In [ ]:
print(pred[:5])
print(y_test[:5])

In [288]:
print(y_test-pred)

[[-6.27150964e+16  5.94870486e+16  2.85694934e+17 ... -7.41745647e+16
  -8.95572138e+15 -7.15285983e+16]
 [-1.73626176e+17 -5.14240307e+16  1.74783855e+17 ... -1.85085644e+17
  -1.19866801e+17 -1.82439678e+17]
 [-1.36437738e+17 -1.42355926e+16  2.11972293e+17 ... -1.47897206e+17
  -8.26783626e+16 -1.45251239e+17]
 ...
 [-1.25214500e+16  1.09680695e+17  3.35888581e+17 ... -2.39809183e+16
   4.12379250e+16 -2.13349519e+16]
 [-2.57872529e+15  1.19623420e+17  3.45831305e+17 ... -1.40381936e+16
   5.11806498e+16 -1.13922271e+16]
 [-1.06989801e+17  1.52123439e+16  2.41420230e+17 ... -1.18449269e+17
  -5.32304261e+16 -1.15803303e+17]]


Dnn

In [289]:
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import regularizers

In [293]:
# Creazione del modello DNN
model = Sequential()
model.add(Dense(32, input_dim=4, activation='relu'))
model.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.02)))
model.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.02)))
model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.02)))
model.add(Dense(1,activation='linear'))




In [294]:
# Compilazione del modello
model.compile(loss='mean_squared_error', optimizer='RMSprop', metrics=['mean_squared_error', 'mean_absolute_error'])
# Addestramento del modello
model.fit(x_train_normalized, y_train_normalized, epochs=600, batch_size=8, verbose=1)
# Inferenza
y_pred_normalized = model.predict(x_test_normalized)
y_pred = abs(scaler_y.inverse_transform(y_pred_normalized))


Epoch 1/600
432/432 [==============================] - 1s 650us/step - loss: 0.8229 - mean_squared_error: 0.2933 - mean_absolute_error: 0.4452
Epoch 2/600
432/432 [==============================] - 0s 641us/step - loss: 0.3223 - mean_squared_error: 0.2922 - mean_absolute_error: 0.4425
Epoch 3/600
432/432 [==============================] - 0s 639us/step - loss: 0.3074 - mean_squared_error: 0.2898 - mean_absolute_error: 0.4412
Epoch 4/600
432/432 [==============================] - 0s 641us/step - loss: 0.3046 - mean_squared_error: 0.2904 - mean_absolute_error: 0.4410
Epoch 5/600
432/432 [==============================] - 0s 640us/step - loss: 0.3017 - mean_squared_error: 0.2886 - mean_absolute_error: 0.4384
Epoch 6/600
432/432 [==============================] - 0s 643us/step - loss: 0.3010 - mean_squared_error: 0.2873 - mean_absolute_error: 0.4366
Epoch 7/600
432/432 [==============================] - 0s 649us/step - loss: 0.2989 - mean_squared_error: 0.2863 - mean_absolute_error: 0.4351

In [295]:
print(y_pred[:5])
print(y_test[:5])

[[9.2866573e+16]
 [1.5398006e+17]
 [1.6809457e+17]
 [4.2987473e+16]
 [1.4918402e+17]]
[1.14595643e+16 1.33661709e+17 3.59869595e+17 7.02110881e+16
 1.94462550e+17]


In [266]:
print(y_pred-y_test)

[[ 6.27150964e+16 -5.94870486e+16 -2.85694934e+17 ...  7.41745647e+16
   8.95572138e+15  7.15285983e+16]
 [ 1.73626176e+17  5.14240307e+16 -1.74783855e+17 ...  1.85085644e+17
   1.19866801e+17  1.82439678e+17]
 [ 1.36437738e+17  1.42355926e+16 -2.11972293e+17 ...  1.47897206e+17
   8.26783626e+16  1.45251239e+17]
 ...
 [ 1.25214500e+16 -1.09680695e+17 -3.35888581e+17 ...  2.39809183e+16
  -4.12379250e+16  2.13349519e+16]
 [ 2.57872529e+15 -1.19623420e+17 -3.45831305e+17 ...  1.40381936e+16
  -5.11806498e+16  1.13922271e+16]
 [ 1.06989801e+17 -1.52123439e+16 -2.41420230e+17 ...  1.18449269e+17
   5.32304261e+16  1.15803303e+17]]


controlloo quali valori vanno meglio

In [278]:
#Programma per capire i valori da inserire nel programma
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor
import numpy as np

# Definizione del range dei valori per i parametri
param_grid = {
    'n_estimators': range(50, 200),
    'max_depth': range(2, 10),
    'reg_lambda': [1, 10, 50, 100]
}

# Creazione del modello

scaler_x = MinMaxScaler(feature_range=(-1, 1))  # Imposta il range di output desiderato (min_value, max_value)
x_train_normalized = scaler_x.fit_transform(x_train)
x_test_normalized = scaler_x.transform(x_test)

#scaler_y =StandardScaler()  
scaler_y = MinMaxScaler(feature_range=(-1, 1))  # Imposta il range di output desiderato (min_value, max_value)
y_train_normalized = scaler_y.fit_transform(y_train.reshape(-1, 1))
y_test_normalized = scaler_y.transform(y_test.reshape(-1, 1))


model = XGBRegressor(seed=1)
# Creazione dell'oggetto RandomizedSearchCV per la ricerca casuale dei parametri
random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_grid,
    scoring='neg_mean_squared_error',  # Utilizza l'MSE come metrica di valutazione
    n_iter=10,  # Numero di combinazioni casuali da provare
    cv=5,  # Numero di fold nella cross-validation
    random_state=1
)

# Addestramento del modello con la ricerca casuale dei parametri
random_search.fit(x_train_normalized, y_train_normalized)

# Stampa dei risultati
print("Migliori parametri:")
print(random_search.best_params_)
print("Miglior punteggio di validazione:")
print(np.sqrt(-random_search.best_score_))

# Valutazione del modello sui dati di test
y_pred = random_search.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
print("Errore quadratico medio sui dati di test:")
print(np.sqrt(mse))


Migliori parametri:
{'reg_lambda': 100, 'n_estimators': 140, 'max_depth': 6}
Miglior punteggio di validazione:
0.4441328057130181
Errore quadratico medio sui dati di test:
1.6364167579435427e+17


In [213]:
from sklearn.ensemble import GradientBoostingRegressor
def classify(x,y,clf=GradientBoostingRegressor(),show=False,alpha=1.):
    idx = np.arange(x.shape[0])
    idx = idx[:int(alpha*x.shape[0])]
    #idx used to pick only a % of the data train
    clf.fit(x_train[idx],y_train[idx])
    pred = clf.predict(x)
   
    print("errors: {:.2f}%".format(100*(1-clf.score(x, y))))
    print("Accuracy: {:.2f}".format(r2_score(y, pred)))
    return (r2_score(y, pred))

In [214]:
acc_XGB=[classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=.2),
         classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=.4),
         classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=.6),
         classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=.8),
         classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=1.)]
acc_XGBt=[classify(x_test_normalized,y_test_normalized,XGBClassifier(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=.2),
          classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=.4),
          classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=.6),
          classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=.8),
          classify(x_test_normalized,y_test_normalized,XGBRegressor(seed=1,reg_lambda=1., n_estimators=145,max_depth=8),show=True,alpha=1.)]

errors: 22243448.24%
Accuracy: -222433.48
errors: 4415095.59%
Accuracy: -44149.96
errors: 32051.41%
Accuracy: -319.51
errors: 225111.54%
Accuracy: -2250.12
errors: 225047.03%
Accuracy: -2249.47


ValueError: Invalid classes inferred from unique values of `y`.  Expected: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171], got [1.198069e+00 1.603553e+00 2.561476e+00 2.734604e+00 3.001480e+00
 3.171514e+00 3.277072e+00 3.355923e+00 3.410681e+00 3.584216e+00
 4.339171e+00 4.424833e+00 6.791152e+00 8.054777e+00 8.158165e+00
 8.528559e+00 9.591210e+00 1.178015e+01 1.264098e+01 1.368761e+01
 1.461909e+01 1.746233e+01 2.202954e+01 2.468734e+01 3.040813e+01
 3.111262e+01 4.038746e+01 4.262643e+01 4.346737e+01 6.512593e+01
 8.770427e+01 8.811471e+01 9.142512e+01 9.837823e+01 1.070975e+02
 1.187811e+02 1.243380e+02 1.340989e+02 1.738892e+02 2.116794e+02
 2.140780e+02 2.201038e+02 2.260323e+02 2.344051e+02 2.583330e+02
 2.611376e+02 2.668908e+02 3.010259e+02 3.077248e+02 3.227726e+02
 3.344727e+02 3.685119e+02 4.140550e+02 4.445874e+02 4.519227e+02
 4.547027e+02 4.768407e+02 4.953395e+02 4.961617e+02 5.151832e+02
 5.761778e+02 7.171543e+02 7.178878e+02 7.208307e+02 7.628950e+02
 7.728083e+02 8.498998e+02 9.685897e+02 9.767304e+02 9.922719e+02
 1.102896e+03 1.114113e+03 1.155407e+03 1.214910e+03 1.221382e+03
 1.264776e+03 1.293212e+03 1.294101e+03 1.403548e+03 1.413081e+03
 1.562655e+03 1.577192e+03 1.682821e+03 1.752955e+03 1.770632e+03
 1.788002e+03 1.873143e+03 1.944011e+03 1.991053e+03 2.019571e+03
 2.212850e+03 2.424041e+03 2.461164e+03 2.491784e+03 2.493630e+03
 2.503639e+03 2.679973e+03 2.710541e+03 2.813002e+03 2.819951e+03
 2.901280e+03 2.932943e+03 2.944027e+03 2.983483e+03 2.991106e+03
 3.086983e+03 3.333554e+03 3.334603e+03 3.341483e+03 3.439341e+03
 3.694092e+03 3.774725e+03 3.787445e+03 3.805435e+03 3.819766e+03
 3.822679e+03 3.898532e+03 3.916943e+03 4.056478e+03 4.175102e+03
 4.473212e+03 4.591515e+03 4.612932e+03 4.935147e+03 5.260771e+03
 5.272478e+03 5.661354e+03 5.883314e+03 5.994415e+03 6.605054e+03
 6.776844e+03 6.862291e+03 6.929012e+03 7.086637e+03 7.116170e+03
 7.122309e+03 7.140801e+03 7.559715e+03 7.675900e+03 8.133766e+03
 8.157405e+03 8.281244e+03 8.575559e+03 8.680795e+03 8.932704e+03
 8.944797e+03 8.962237e+03 8.986065e+03 9.022925e+03 9.276594e+03
 9.311861e+03 9.449345e+03 9.643253e+03 9.939035e+03 1.007026e+04
 1.026402e+04 1.035556e+04 1.105691e+04 1.130374e+04 1.157840e+04
 1.188319e+04 1.215523e+04 1.229742e+04 1.238598e+04 1.239132e+04
 1.254662e+04 1.281762e+04 1.287626e+04 1.310928e+04 1.313510e+04
 1.369744e+04 1.379050e+04]

In [197]:
from sklearn.metrics import r2_score

def accuracy_t(x,y,model,show=False,alpha=1.):
    
 
    idx = np.arange(x.shape[0])
    idx = idx[:int(alpha*x.shape[0])]
    #Dnn
    model.compile(loss='mean_squared_error', optimizer='RMSprop',metrics=['accuracy'])#optimizer='RMSprop',
    fit=model.fit(x[idx], y[idx], epochs=600, batch_size=8, verbose=1)
    pred = model.predict(x)
    pred = abs(scaler_y.inverse_transform(pred))
    print(pred)    
    print("Accuracy: {:.2f}".format(r2_score(y, pred)))
    print("errors: {:.2f}%".format(mean_squared_error(pred, y)*100))
    #XGBoost
    
    return r2_score(y, pred)


In [198]:
acc_DNN=[accuracy_t(x_test_normalized,y_test_normalized,model,show=False,alpha=.2),accuracy_t(x_test_normalized,y_test_normalized,model,show=False,alpha=.4),accuracy_t(x_test_normalized,y_test_normalized,model,show=False,alpha=.6),accuracy_t(x_test_normalized,y_test_normalized,model,show=False,alpha=.8),accuracy_t(x_test_normalized,y_test_normalized,model,show=False,alpha=1.)]
acc_tDNN=[accuracy_t(x_train_normalized,y_train_normalized,model,show=False,alpha=.2),accuracy_t(x_train_normalized,y_train_normalized,model,show=False,alpha=.4),accuracy_t(x_train_normalized,y_train_normalized,model,show=False,alpha=.6),accuracy_t(x_train_normalized,y_train_normalized,model,show=False,alpha=.8),accuracy_t(x_train_normalized,y_train_normalized,model,show=False,alpha=1.)]

Epoch 1/600
22/22 [==============================] - 0s 992us/step - loss: 0.2063 - accuracy: 0.0000e+00
Epoch 2/600
22/22 [==============================] - 0s 912us/step - loss: 0.2016 - accuracy: 0.0000e+00
Epoch 3/600
22/22 [==============================] - 0s 1ms/step - loss: 0.2016 - accuracy: 0.0000e+00
Epoch 4/600
22/22 [==============================] - 0s 1ms/step - loss: 0.2021 - accuracy: 0.0000e+00
Epoch 5/600
22/22 [==============================] - 0s 863us/step - loss: 0.1985 - accuracy: 0.0000e+00
Epoch 6/600
22/22 [==============================] - 0s 832us/step - loss: 0.1976 - accuracy: 0.0000e+00
Epoch 7/600
22/22 [==============================] - 0s 953us/step - loss: 0.1993 - accuracy: 0.0000e+00
Epoch 8/600
22/22 [==============================] - 0s 860us/step - loss: 0.1976 - accuracy: 0.0000e+00
Epoch 9/600
22/22 [==============================] - 0s 823us/step - loss: 0.1967 - accuracy: 0.0000e+00
Epoch 10/600
22/22 [==============================] - 0s 85

KeyboardInterrupt: 

In [ ]:
x=[.2,.4,.6,.8,1.]
fig, ax=plt.subplots(nrows=1, ncols=2)
fig.set_size_inches(15, 7.5)
#ax[1].plot(x,acc_XGB,label='XGB')
ax[1].plot(x,acc_DNN,label='DNN')
ax[1].set_title('Comparison accuracy test data sample ')
ax[1].set_xlabel('percentage of data test')
ax[1].set_ylabel('Accuracy')

#ax[0].plot(x,acc_XGBt,label='XGB')
ax[0].plot(x,acc_tDNN,label='DNN')
ax[0].set_title('Comparison accuracy train data sample ')
ax[0].set_xlabel('percentage of data train')
ax[0].set_ylabel('Accuracy')
plt.legend()
plt.show()
#alp=x[acc_XGB.index(max(acc_XGB))]

#print('the max accuracy of XGB is:',max(acc_XGB),'found with the percentage',x[acc_XGB.index(max(acc_XGB))],'of data test')
print('the max accuracy of DNN is:',max(acc_DNN),'found with the percentage',x[acc_DNN.index(max(acc_DNN))],'of data test')

#print('the max accuracy of XGB is:',max(acc_XGBt),'found with the percentage',x[acc_XGBt.index(max(acc_XGBt))],'of data train')
print('the max accuracy of DNN is:',max(acc_tDNN),'found with the percentage',x[acc_tDNN.index(max(acc_tDNN))],'of data train')